[window]
padding={x=4,y=4}
opacity=0.78
# opacity=0
blur=true

[font]
size=9
normal={family='Monaspace Neon NF', style='regular'}

[mouse]
hide_when_typing=true

# [colors]
# [colors.primary]
# background="#cccccc"

