# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# format = '''
# [┌](bold green)$directory$git_branch
# [└─>](bold green) '''

#┘
#┐
#┌

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[|](bold #add3ff)' # The 'success_symbol' segment is being set to '󱞩' with the color 'bold green'
error_symbol = '[|](bold #ff9da4)' # The 'success_symbol' segment is being set to '󱞩' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]#Module
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = '[ ](bold #ff9da4)'
style="#b392f0"

